export const APP_SIGNALS = {
  SET_ZOOM: 'SET_ZOOM',
  GET_ZOOM: 'GET_ZOOM',
  GET_FIGURES: 'GET_FIGURES',
  ADD_PERSON: 'ADD_PERSON',
  UPDATE_PERSON_POSITION: 'UPDATE_PERSON_POSITION',
  GET_CANVAS_POSITION: 'GET_CANVAS_POSITION',
  SAVE_CANVAS_POSITION: 'SAVE_CANVAS_POSITION',
  GET_ALL_CONNECTIONS: 'GET_ALL_CONNECTIONS',
  ADD_CONNECTION: 'ADD_CONNECTION',
  DELETE_CONNECTION: 'DELETE_CONNECTION',
  DELETE_FIGURE: 'DELETE_FIGURE',

  UPDATE_FIGURE_NAME: 'UPDATE_FIGURE_NAME',
  OPEN_APP: 'OPEN_APP',
};
